spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

security:
  jwt:
    base64-secret: TRrx3ZoD9xgevlM73MU8/ay9VO+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfP94DH6jBxBhFyBPaQQQ==
    access-token-validity-in-seconds: 300000
    refresh-token-validity-in-seconds: 300000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    # Your package
    com.booking.userservice.config: DEBUG
    com.booking.userservice.config.HeaderBasedAuthenticationFilter: DEBUG
    com.booking.userservice.config.SecurityConfiguration: DEBUG

    # Spring Security
    org.springframework.security: DEBUG

    # Servlet filter / Dispatcher
    org.springframework.web.filter: DEBUG
    org.springframework.web.servlet: DEBUG

    # HTTP requests / headers (optional)
    org.springframework.web: DEBUG

    # Optional: underlying logging libraries
    org.hibernate.SQL: DEBUG        # if you want DB queries logged
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # bind parameters

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
