name: Java CI (Multi-Module Maven)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # Step 3: Build all modules
      - name: Build project with Maven
        run: mvn -B clean install

      # Step 4: Save built JAR files as artifacts
      - name: Upload JAR files
        uses: actions/upload-artifact@v4
        with:
          name: booking-system-jars
          path: |
            **/target/*.jar
            !**/target/*-sources.jar
            !**/target/*-javadoc.jar
